## -- Note -- ##
# Instead of running it using `docker-compose up`, please execute it with :
#  $ docker-compose build
#  $ docker-compose run insta

#  Here you first build the docker image from the Dockerfile then run a service named 'insta' in docker-compose.yml.
#  Reason : `docker-compose up` is not interactive (https://github.com/docker/compose/issues/3081#issuecomment-193428350).

version: '3.8'

services: 
  insta:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instagram_profpic_downloader
    # This must be present and set to true, otherwise the app can not receive user input (instagram username)
    stdin_open: true
    volumes: ['./:/app']