## Note ##
# Instead of running it using `docker-compose up`, please execute it with `docker-compose run insta` 
#  whereas 'insta' is the service name in docker-compose.yml.
#  Reason : `docker-compose up` is not interactive (https://github.com/docker/compose/issues/3081#issuecomment-193428350).
##########

version: '3.8'

services: 
  insta:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instagram_profpic_downloader
    # This must be present and set to true, otherwise the app can not receive user input (instagram username)
    stdin_open: true
    volumes: ['./:/app']